## Vectorization Demo

In [1]:
import numpy as np

a = np.array([1,2,3,4])
print(a)

[1 2 3 4]


In [9]:
import time

#Vectorized
a = np.random.rand(1000000)
b = np.random.rand(1000000)

tic = time.time()
c = np.dot(a,b)
toc = time.time()

print(c)
print("Vectorized version:" + str(1000*(toc-tic)) + "ms")

#For loop
c = 0
tic = time.time()
for i in range(1000000):
    c += a[i]*b[i]
toc = time.time()

print(c)
print("For loop:" + str(1000*(toc-tic)) + "ms")

249856.38433346513
Vectorized version:0.8730888366699219ms
249856.38433346016
For loop:673.694372177124ms


## Broadcasting Example

In [11]:
import numpy as np

A = np.array([[56.0, 0.0, 4.4, 68.0],
             [1.2, 104.0, 52.0, 8.0],
             [1.8, 135.0, 99.0, 0.9]])
print(A)

[[ 56.    0.    4.4  68. ]
 [  1.2 104.   52.    8. ]
 [  1.8 135.   99.    0.9]]


In [12]:
cal = A.sum(axis=0) #垂直求和
print(cal)

[ 59.  239.  155.4  76.9]


In [13]:
percentage = 100*A/cal.reshape(1,4) #O(1)调用成本低
print(percentage)

[[94.91525424  0.          2.83140283 88.42652796]
 [ 2.03389831 43.51464435 33.46203346 10.40312094]
 [ 3.05084746 56.48535565 63.70656371  1.17035111]]


## Python/Numpy Vectors

In [1]:
import numpy as np

a = np.random.randn(5)

In [2]:
print(a)

[-0.57708361  1.67611219  0.21066047 -2.66396996  0.26759867]


In [3]:
print(a.shape) #rank 1 array 不要使用

(5,)


In [4]:
print(a.T) #一组"[]"，rank 1 array既不是行向量也不是列向量 不要使用

[-0.57708361  1.67611219  0.21066047 -2.66396996  0.26759867]


In [5]:
print(np.dot(a,a.T))

10.355100396426224


In [7]:
a = np.random.randn(5,1) #column vector。若是(1,5)，row vector。可以使用
print(a)

[[ 1.54585066]
 [-1.3371482 ]
 [-1.5587093 ]
 [-0.42277318]
 [ 0.50303264]]


In [8]:
print(a.T) #两组"[]"，1*5矩阵

[[ 1.54585066 -1.3371482  -1.5587093  -0.42277318  0.50303264]]


In [9]:
print(np.dot(a,a.T))

[[ 2.38965426 -2.06703143 -2.4095318  -0.6535442   0.77761334]
 [-2.06703143  1.78796531  2.08422534  0.5653104  -0.67262919]
 [-2.4095318   2.08422534  2.42957469  0.65898049 -0.78408166]
 [-0.6535442   0.5653104   0.65898049  0.17873716 -0.21266871]
 [ 0.77761334 -0.67262919 -0.78408166 -0.21266871  0.25304184]]


不太确定某一向量的维度：

In [ ]:
assert (a.shape == (5,1))

若出现rank 1 array：

In [ ]:
a = a.reshape((5,1))

In [16]:
a = np.random.randn(3, 3)
b = np.random.randn(3, 1)
c = a*b
print("a:"+ str(a)+"\n","b:"+str(b)+"\n","c:"+str(c))

a:[[ 1.11137621  2.52236261 -0.30266617]
 [ 1.04264483  1.81774632 -1.4122313 ]
 [-1.352767   -0.14281007 -0.1725813 ]]
 b:[[-0.05491857]
 [ 0.33717873]
 [-0.97841305]]
 c:[[-0.06103519 -0.13852454  0.01662199]
 [ 0.35155766  0.61290541 -0.47617436]
 [ 1.32356489  0.13972724  0.1688558 ]]


In [18]:
print(c.shape)

(3, 3)
